#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr arrange
#' @importFrom dplyr case_when
#' @importFrom dplyr filter
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_line
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom magrittr %>%
#' @importFrom reactable colDef
#' @importFrom reactable JS
#' @importFrom reactable reactable
#' @importFrom reactable reactableLang
#' @importFrom reactable reactableOutput
#' @importFrom reactable renderReactable
#' @importFrom shiny actionButton
#' @importFrom shiny br
#' @importFrom shiny checkboxGroupInput
#' @importFrom shiny column
#' @importFrom shiny div
#' @importFrom shiny fluidPage
#' @importFrom shiny fluidRow
#' @importFrom shiny h1
#' @importFrom shiny h3
#' @importFrom shiny img
#' @importFrom shiny mainPanel
#' @importFrom shiny navbarPage
#' @importFrom shiny plotOutput
#' @importFrom shiny selectInput
#' @importFrom shiny shinyApp
#' @importFrom shiny sidebarLayout
#' @importFrom shiny sidebarPanel
#' @importFrom shiny sliderInput
#' @importFrom shiny strong
#' @importFrom shiny tabPanel
#' @importFrom shiny titlePanel
#' @importFrom shinyjs useShinyjs
## usethis namespace: end
NULL
